version: "2"
# Prerender is not meant to run on swarm mode, thus 2.x version (as swarm mode is not supporting
# kernel capabilities as of now), it will be deployed separately to Amazon ECS though and used for every project

services:
  prerender:
    image: heathmont/prerender-chrome:5.1.0
    ports:
      - 80:80/tcp
    environment:
      PORT: "80"
      LOG_REQUESTS: "1"
      BLOCKED_RESOURCES_DOMAINS: "asset.games-assets.xyz,elecgames-static.casinomodule.com,quickfire3.gameassists.co.uk,radar.cedexis.com,mob3.gcontent.eu,api.gameassists.co.uk,prod.onetouch.io,lobby-mbet.betsoftgaming.com,demo.endorphina.network,d22qnm33zunn5d.cloudfront.net,ga1.game-program.com,caocw.playngonetwork.com,caodemo.playngonetwork.com"
    cap_add:
      - SYS_ADMIN
    labels:
      ops.ecs_desired_count: "1"
      ops.health_check_path: "/https://bitcasino.io"
      ops.ecs_lb_scheme: "internet-facing"
